"use client"
import type { Metadata } from "next";
import "./globals.css";
import NavbarWrapper from "@/components/layout/NavbarWrapper";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/layout/Navigation";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});
// export const metadata: Metadata = {
//   title: "Inventery",
//   description: "Generated by create next app",
// };

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { usePathname } from "next/navigation";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const queryClient = new QueryClient();
  const pathname = usePathname();
  const pathParts = pathname.split("/").filter(Boolean);

  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        
        <body className={`${roboto.variable} min-h-screen`}>
          <Navigation/>
          <div className="flex  bg-[#F3F4F6] min-h-screen    w-screen ">
            
            <NavbarWrapper />
            
            <div className={`w-full bg-[#F3F4F6] flex  h-min px-8  pb-[100px]  ml-[256px] pt-[150px]`}>
              {children}
            </div>
          </div>
        </body>
      </QueryClientProvider>
    </html>
  );
}
