"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/layout/NavbarWrapper";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/layout/Navigation";
import { useState } from "react";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});
// export const metadata: Metadata = {
//   title: "Inventery",
//   description: "Generated by create next app",
// };

import {
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [navbar, setNavbar] = useState<boolean>(false);

  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body className={`${roboto.variable} min-h-screen`}>
          <Navigation />
          {!navbar && (
            <div className=" flex   bg-[#F3F4F6]">
              <button
                onClick={() => setNavbar(true)}
                className="bg-[#CFDBE6] h-[50px] w-[50px] flex flex-col items-center justify-center gap-1.5 rounded-[6px] hover:cursor-pointer z-50  ml-[280px] mt-[20px] "
              >
                <div className="h-[4px] w-[30px] bg-[#0F4C81] rounded-[10px]"></div>
                <div className="h-[4px] w-[30px] bg-[#0F4C81] rounded-[10px]"></div>
                <div className="h-[4px] w-[30px] bg-[#0F4C81] rounded-[10px]"></div>
              </button>
            </div>
          )}

          <div className="flex min-h-screen bg-[#F3F4F6]  relative">
            {navbar && <NavbarWrapper />}

            <div className="w-full max-w-[1440px] mx-auto p-8">{children}</div>
          </div>
        </body>
      </QueryClientProvider>
    </html>
  );
}
